# Site settings
description: A blog about program
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.fanxy.me" # the base hostname & protocol for your site 
timezone: Asia/Shanghai
encoding: utf-8
# Outputting
permalink:     date
paginate_path: /page:num

# User settings
username: Fanxy
user_description: Fanxy at Shanghai
user_title: Developer
email: LuciferFan913@gmail.com
t#witter_username: null
github_username:  CFanxy
disqus_username: cfanxy

# Build settings
markdown: kramdown
permalink: /:title/

#karmdown
karmdown: 
  input: GFM  #GitHub favored markdown extensions
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  hard_wrap:      false
  footnote_nr:    1


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
