# Site settings
description: A blog about java develop
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site 
timezone: Asia/Shanghai
encoding: utf-8

# User settings
username: Fanxy
user_description: Fanxy at Shanghai
user_title: backend Developer
email: Charles.Fan@foxmail.com
t#witter_username: lorem_ipsum
github_username:  CharlesFan913
#gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/

#karmdown
karmdown: 
  input: GFM  #GitHub favored markdown extensions


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
